SUPABASE_URL = "https://tjpchtglooimlgjeumie.supabase.co/rest/v1/"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqcGNodGdsb29pbWxnamV1bWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NDEzNjEsImV4cCI6MjA4ODAxNzM2MX0.HiqMNJq9exoAsRw4yQ3UgR_c3HcwWmKngh_8XNxlZVM"
